version: 2
updates:
  # Backend dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      typescript-types:
        patterns:
          - "@types/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      fastify:
        patterns:
          - "fastify"
          - "@fastify/*"
        update-types:
          - "minor"
          - "patch"
      database:
        patterns:
          - "pg"
          - "typeorm"
          - "@types/pg"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "supertest"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "puppeteer"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    versioning-strategy: "auto"
    rebase-strategy: "auto"
    target-branch: "develop"

  # Frontend dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      testing-library:
        patterns:
          - "@testing-library/*"
        update-types:
          - "minor"
          - "patch"
      state-management:
        patterns:
          - "redux"
          - "@reduxjs/*"
          - "reselect"
        update-types:
          - "minor"
          - "patch"
      ui-components:
        patterns:
          - "@mui/*"
          - "@emotion/*"
        update-types:
          - "minor"
          - "patch"
    versioning-strategy: "auto"
    rebase-strategy: "auto"
    target-branch: "develop"

  # GitHub Actions workflow dependencies configuration
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    groups:
      actions:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
      github:
        patterns:
          - "github/*"
        update-types:
          - "minor"
          - "patch"
    versioning-strategy: "auto"
    rebase-strategy: "auto"
    target-branch: "develop"